package com.tmsbackend.domain.model;

public enum AuditEventType {
    LOGIN,
    LOGOUT,
    ANNUNCIATION_ACK,
    AVR_MODE_CHANGE,
    TAP_RAISE,
    TAP_LOWER,
    CONTROL_FAIL_RESET,
    AVR_SETTING_CHANGE,
    DEVICE2243_SETPOINT_CHANGE,
    MAIL_CONFIG_CHANGE,
    THRESHOLD_BREACH,
    MAIL_SENT,
    USER_CREATED,
    USER_UPDATED,
    USER_STATUS_CHANGED,
    USER_DELETED,
    ROLE_CREATED,
    ROLE_DELETED
}
